# Generated by Django 5.1.4 on 2024-12-14 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0002_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleeprecord',
            name='wake_up_reason',
        ),
        migrations.AlterField(
            model_name='sleeprecord',
            name='wake_ups',
            field=models.IntegerField(),
        ),
    ]
