# Generated by Django 5.1.4 on 2024-12-15 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep', '0007_alter_diethabit_calories_alter_diethabit_food_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalactivity',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='physicalactivity',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_activities', to='sleep.userprofile'),
        ),
    ]
